//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactorManagmentG13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorCommodity
    {
        public int CommodityID { get; set; }
        public int FactorID { get; set; }
        public int PriceInDay { get; set; }
        public int Number { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual Factor Factor { get; set; }
    }
}
